[program:phytograph]
command=python3 /home/user/webapp/backend/main.py
directory=/home/user/webapp
autostart=true
autorestart=true
stderr_logfile=/home/user/webapp/logs/err.log
stdout_logfile=/home/user/webapp/logs/out.log
